version: '3.4'

services:
  clancommander.discordbot:
    image: ${DOCKER_REGISTRY-}clancommanderdiscordbot
    build:
      context: .
      dockerfile: src/ClanCommander.DiscordBot/Dockerfile
    environment:
      - Discord__BotToken=
      - Discord__BotOwnerId=0
      - Discord__DevGuildId=0
      - ConnectionStrings__PostgreSQL=Host=db;Port=5432;Database=discord_guild;Username=postgres;Password=postgres;
      - ConnectionStrings__Redis=redis-server:6379
      - ClashOfClansAPI__Token=
    depends_on:
      - db
      - redis-server
  db:
    image: postgres:12.10-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=discord_guild
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis-server:
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data: