global using ClanCommander.ApplicationCore.Entities.ClashOfClans;
global using ClanCommander.ApplicationCore.Entities.Discord.Guilds;
global using ClanCommander.ApplicationCore.Entities.Discord.Users;
global using ClanCommander.ApplicationCore.Entities.DiscordClashOfClans.Clans;
global using ClanCommander.ApplicationCore.Entities.DiscordClashOfClans.Users;
global using ClanCommander.ApplicationCore.Entities.MessageCommands;
global using FluentAssertions;
global using System;
global using System.Collections.Generic;
global using Xunit;
global using static FluentAssertions.FluentActions;
